#!/usr/bin/env python3

import boto3
import os
import pexpect
import json

# Prompt for MFA time-based one-time password (TOTP)
mfa_TOTP = input("Enter the MFA code: ")

session = boto3.session.Session(profile_name='dev')


sts_connection = session.client('sts');

# Use the appropriate device ID (serial number for hardware device or ARN for virtual device).
# Replace ACCOUNT-NUMBER-WITHOUT-HYPHENS and MFA-DEVICE-ID with appropriate values.

tempCredentials = sts_connection.get_session_token(
          DurationSeconds=900,
          SerialNumber='arn:aws:iam::948591845834:mfa/awsiq',
                  TokenCode=mfa_TOTP
                    )

print(tempCredentials['Credentials']['AccessKeyId'])
print(tempCredentials['Credentials']['SecretAccessKey'])
print(tempCredentials['Credentials']['SessionToken'])

os.environ['AWS_ACCESS_KEY_ID']=tempCredentials['Credentials']['AccessKeyId']
os.environ['AWS_SECRET_ACCESS_KEY']=tempCredentials['Credentials']['SecretAccessKey']
os.environ['AWS_SESSION_TOKEN']=tempCredentials['Credentials']['SessionToken']

os.system('bash ')
